version: '3'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    container_name: Postgresql Database Container
  web:
    build: ./django
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/webapp
    ports:
      - "8000:8000"
    depends_on:
      - db
    container_name: Django Main Container
