name: geolrecap
description: GeolRecap Application
version: 2.0.0+1
environment:
  sdk: ">=2.1.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  # Main Database
  sqflite: ^1.3.0
  path_provider: ^1.6.7 # Use with sqflite
  ext_storage: ^1.0.3
  permission_handler: ^5.0.0+hotfix.8
  # Text Editor
  zefyr: ^0.10.0
  image_picker: ^0.6.5+3 # Use with Zefyr Image Delegate
  photo_view: ^0.9.2 # Photo View
  # Bloc
  flutter_bloc: ^4.0.0
  equatable: ^1.1.1
  # Position Get
  location: ^3.0.2
  utm: ^0.1.2
  # Date Format
  intl: ^0.16.1
  # Other
  http: ^0.12.1
  csv: ^4.0.3
  share: ^0.6.4+2
  esys_flutter_share: ^1.0.2
  flutter_share: ^1.0.2+1
  flutter_slidable: ^0.5.4 # Use in list slide actions
  sqflite_porter:
    git:
      url: git://github.com/tekartik/sqflite_more
      ref: dart2
      path: sqflite_porter
    version: ">=0.2.0"
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/database/
  #  - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
